language: node_js
node_js:
- node

services:
- postgresql

cache: npm

before_script:
- psql -c 'create database test-ninjas;' -U postgres

script: npm run migrate

env:
  global:
  - NODE_ENV=test
  - secure: QJYNjSm3NdckY83xMWAcfVA7Zb1oAgIJlg5EuZJw0/4LiroGUT0Xb9oKvT7RKedtxOEDUp7y1GavMoj/xKJNoPZx9E/GHosHyb3bf2QwS5QBbgJM0+/M4Bsufyl3I/8qDtW9u/xcZgn6+Ee6bpJtrErMzztEGMAeTLIRnOlxhlEREHl3ziZF3/3v/XhVItqW5OzxVT2r0yQlQXa7m95AmXXp815XcBashK042xY5y7jSZzWMOIVBMis+MRYjCyh2xqD/nFJRDbvsy99j78R9LizL9igREcq9qvWydny+DlfHsoVzjZNkNG5iqXk7f9gNoSpWgbciXpM6kGcu529NMx7VYC/3z7j1GIbrdKZ+eSzPKJ/8flH4csCM4cerBk9eomqc5cCgxN/yrfTTWH0N7i5tzoxVEAF8hokz2fA7L3MUYigIUza0n32sVrGQ0paFKc6Z40utU3kk+DATedGleGWyibgDt9DyhHwcf6jzhXaVbF/KQSFnq6PMRuZExaqAs3aQ4G0gwNO1z1ASOWF4OQzf1cVpVaAs9wHiVA0RRp7/FnlW+W+wEZTs9pT+edjwcVVQnLnNFLTy6TI5zbwrjhbf5CdV4W5U24zL9Y7Gw8AqmYUFJYjYkfsODk6rMBBM7R4J73xuG2X/sCd5GdMM1lDtYHYf/oVA6H40dw26WW4=
  - secure: VZeR8jCjm8IWVeT4QIVcO/0I6OUP4ak90RvzqoFG4LjwJ0Yytl7wdwOrWN4jRMoH9iKiDCx3KIK77rSQFL9vkOpQ5QJ2+Zx3IXfYO28V87T54rDhS21Yhvuox6iMGDwih5O4NGMPc/HRARNCn1btC3de1QUorFrFvcscwiIhbvF7QYQ8hU0pl3OCxQcOr+trlRmYsD/XnJc6SbVu+LfCXEyu74VsRFTXGxLc0xtVvdL7yEHaFHk0mLkKf3QfWsHZkOtba6D/k1xUi4Y1MrEHE8WTCDGhs2RSV6gAzcZ71x3BloZnS4IZIXzMzP/u+hgUYBf9CBadM+nudNMSnQ67YYjZJM8+qdOZHBo+MWAYtnQr5QaorUo53jDW/QbKoLVl7ztqN8zD6wEpiomUQjepMypAKCnuC16ArmTJ4P5Dht3IpU6No+kMX7sa+sMU9UldfzNbC7OBQINj4vSkstv68yH6SjbdhIM7PYQgIpHqJVP4XYk1ZYiDSyhKRyMGvbFLP412kLEHyapdRuHRFp+mBYJXqhGHwqb0p1duqnYolbthq7pcTkPQlCboATnL8fJ0+qrc6qYeDo5KRmHQcKsEE9E6jzihtFVIniQLdr11mTt1JN18wZWq+y9D8VDmoN8Zs7NgcgZe4ngGInG9T9mPPsuzLyGjqxoENnpmdqbkHqs=
  - secure: O/34zctUcOX8gRPPR2iUC5RyDy4igBaM1M+rkwA7d+ZcoZ35phZPcEzdgOGaw/4jMV63yD6jo+frWzUohBB5NrtffsBZ2Q8rOiWMnADaatYhHXanfjbQScnVl92oIiOQjY7kbEkkO1+Rpl+eaV0ndgSg3M+eknFNt50ryroxC+Nw/vSy9RN+LlJzgxZATgKwPb9c5j2aZXRU12zj5IJu1YiDHY90YXy9rPput+1933auE9ryu5bC7X7Fr7TlYcGpmq2tsl/iKsj/UGe/0UZdxnJrQob9eOQXnoybMvuNninpTLGkic/s08hGj+IriRakfRThe8aTjTkcqxKnAQtmiUg5g8Tf/cYpv7KLdUKMnNm94mgaHSSV3y8xUi9GCvz73XzBZ50S6KOqmlfqRiTvy8+varUn0iWimqz4Dx5pHPuTPQXqq2B81h5YVSeBV2qqIIQo3NCgvohqAB9EO8vmV1o6zbynDCQKT+RQGhS83WuCt9hoetHgTh2/I5YymotkxBV5nGUswdFpM1U7fBcrwJ5RM0nfIp+um7UC5W1Ixw9QY6dkq3j2E5HGZVypRftimwhRV/V05wRe+NkjkbINccMHjpwV53g5tEYuG8pJGTqFLh6FzarcL05nuttfGvTygY+mqgZvgmmmY2eiLwPygXc33iPiOZkLDWgB7k2wvDY=

